const ProjectActionTypes = {
    TOGGLE_PROJECT_CATEGORY_1:'TOGGLE_PROJECT_CATEGORY_1',
    TOGGLE_PROJECT_CATEGORY_2:'TOGGLE_PROJECT_CATEGORY_2',
    SET_SLIDER_INDEX:'SET_SLIDER_INDEX',
    APPEAR_SLIDER:'APPEAR_SLIDER',
    HIDDEN_SLIDER:'HIDDEN_SLIDER',
}

export default ProjectActionTypes;